{% set name = "particle-tracking-manager" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/particle_tracking_manager-{{ version }}.tar.gz
  sha256: 4486510ad37f28c728467afa9d5ed092a5d486166a624f54c7deab5a05d087ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.9
    - numpy
    - opendrift
    - pandas
    - xarray

test:
  imports:
    - particle_tracking_manager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/particle-tracking-manager
  summary: Manager for particle tracking simulations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
